on: push

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: PORT
        issuetype: Task
        summary: Build completed for ${{ github.repository }}
        description: Compare branch
        fields: '{"description": "Show an example of how to create jira issue using github action"}'
      
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
