name: Manage GKE Cluster

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Cluster Name'
        required: true
      repo_ulr_for_argo: 
        description: 'The URL of the repository for Argo CD to deploy GKE'
        required: true
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)
        type: string

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Argo CD CLI
      run: |
        sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo chmod +x /usr/local/bin/argocd

    - name: Login to Argo CD
      run: argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASS }} --grpc-web

    - name: Register Repository in Argo CD
      run: argocd repo add ${{ github.event.inputs.repoURLforArgo }} --username samgabrail --password ${{ secrets.MYGITHUB_TOKEN }}

    - name: Check Directory
      run: |
        pwd
        ls -lah
        whoami

    - name: Deploy Cluster with Argo CD
      run: |
          argocd app create ${{ github.event.inputs.cluster_name }} \
            --repo ${{ github.event.inputs.repo_ulr_for_argo }} \
            --path . \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace ${{ github.event.inputs.cluster_name }} \
            --project default \
            --sync-policy automated \
            --sync-option CreateNamespace=true \
            --upsert \
            --grpc-web
