name: Ingest DORA Metrics

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: 'Comma-separated list of repositories to analyze'
        required: true
      timeFrame:
        description: 'Last X weeks'
        required: true
        default: '4'  # Default to the last 4 weeks

jobs:
  compute-dora-metrics:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(github.event.inputs.repositories) }}
    
    steps:
      - name: Deployment Frequency
        id: deploymement_frequency
        uses: DeveloperMetrics/deployment-frequency@main
        with:
          workflows: 'CI/CD'
          owner-repo: '${{ matrix.repo }}'
          pat-token: ${{ secrets.PATTOKEN }}
      
      - name: Results for Deployment Frequency
        run: echo '${{ toJson(steps.deploymement_frequency.outputs)}}'
          
      - name: Lead Time For Changes
        id: lead_time_for_changes
        uses: DeveloperMetrics/lead-time-for-changes@main
        with:
          workflows: 'CI/CD'
          owner-repo: ${{ matrix.repo }}
          pat-token: ${{ secrets.PATTOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install httpx
          pip install PyGithub datetime

      - name: Calculate PR Metrics
        id: metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the automatically provided GITHUB_TOKEN
          REPOSITORY: ${{ matrix.repo }}
          TIME_FRAME: ${{ github.event.inputs.timeFrame }}
        run: python calculate_pr_metrics.py
      
      - name: Calculated Metrics
        run: echo '${{ steps.metrics.outputs.metrics}}'
