name: Ingest DORA Metrics

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      owner: ${{ steps.set-matrix.outputs.owner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read Config and Output Matrix
        id: set-matrix
        run: |
          CONFIG_JSON=$(jq -c . src/dora-config-v2.json)
          MATRIX_JSON=$(echo $CONFIG_JSON | jq -c '[.[] | .items[]]')
          OWNER=$(echo $CONFIG_JSON | jq -r '.[0].owner')
          echo "matrix=${MATRIX_JSON}" >> $GITHUB_OUTPUT
          echo "owner=${OWNER}" >> $GITHUB_ENV

      - name: Debug Owner and Matrix
        run: |
          echo "Owner: $OWNER"
          echo "Matrix: $MATRIX_JSON"

  compute-team-metrics:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Debug Owner
        run: |
          echo "Owner from setup: ${{ needs.setup.outputs.owner }}"
          echo "Owner from env: ${{ env.owner }}"
          
      - name: Compute Team Metrics
        run: |
          python src/calculate_team_metrics.py --owner "${{ needs.setup.outputs.owner }}" --time-frame 14 --token "${{ secrets.GH_TEAM_ACCESS_TOKEN }}" --port-client-id "${{ secrets.PORT_CLIENT_ID }}" --port-client-secret "${{ secrets.PORT_CLIENT_SECRET }}"

  compute-repo-metrics:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}

      - name: Debug Repository and Owner
        run: |
          echo "Repository: ${{ matrix.repository }}"
          echo "Owner: ${{ needs.setup.outputs.owner }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Compute PR Metrics
        run: |
          python src/calculate_pr_metrics.py  --owner "${{ needs.setup.outputs.owner }}" --repo "${{ matrix.repository }}" --token "${{ secrets.GH_TEAM_ACCESS_TOKEN }}" --timeframe "${{ env.TIMEFRAME_IN_DAYS }}" --platform github-actions
          
      # - name: Deployment Frequency
      #   id: deployment_frequency
      #   run: python src/deployment_frequency.py --owner "${{ needs.setup.outputs.owner }}" --repo "${{ matrix.repository }}" --token "${{ secrets.PATTOKEN }}" --workflows '${{ toJson(matrix.workflows) }}' --timeframe "${{ env.TIMEFRAME_IN_DAYS }}" --branch "${{ matrix.branch }}" --platform github-actions
      
      # - name: Lead Time For Changes
      #   id: lead_time_for_changes
      #   run: python src/lead_time_for_changes.py --owner "${{ needs.setup.outputs.owner }}" --repo "${{ matrix.repository }}" --token "${{ secrets.PATTOKEN }}" --workflows '${{ toJson(matrix.workflows) }}' --timeframe ${{ env.TIMEFRAME_IN_DAYS }} --branch ${{ matrix.branch }} --platform github-actions

      # - name: UPSERT Repository DORA Metrics
      #   uses: port-labs/port-github-action@v1
      #   with:
      #     identifier: ${{ fromJson(env.metrics).id }}
      #     title:
