on:
    workflow_dispatch:
    # schedule:
    #     - cron: '0 */1 * * *' # Determines the scheduled interval for this workflow. This example runs every hour.

jobs:
    run-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Run Launchdarkly Integration
              uses: port-labs/ocean-sail@v1
              with:
                type: lauchdarkly
                port_client_id: ${{ secrets.PORT_CLIENT_ID }}
                port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
                config: |
                    launchdarkly_host: "https://launchdarkly.com"
                    launchdarkly_token: {{ secrets.LAUNCHDARKLY_ACCESS_TOKEN }}
