name: Open Slack Channel
on:
  workflow_dispatch:
    inputs:
      channel_name:
        description: Name of the public or private channel to create.
        required: true
        type: string
      is_private:
        description: Create a private channel instead of a public one.
        required: false
        type: boolean
      team_id:
        description: Encoded team ID to create the channel in, required if org token is used.
        type: string
        required: false
      members:
        description: Add members manually to the channel.
        type: array
        required: false
      port_payload:
        description: Port's payload, including details for who triggered the action and general context (blueprint, run ID, etc...).
        required: true

jobs:
  open-slack-channel:
    runs-on: ubuntu-latest
    steps:
      - name: Log Executing Request to Open Channel
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(github.event.inputs.port_payload).context.runId }}
          logMessage: "About to create a conversation channel in slack..."

      # - name: Create Slack Channel
      #   id: create_channel
      #   env:
      #     SLACK_TOKEN: ${{ secrets.BOT_USER_OAUTH_TOKEN }}
      #   run: |
      #     response=$(curl -s -X POST "https://slack.com/api/conversations.create" \
      #       -H "Authorization: Bearer $SLACK_TOKEN" \
      #       -H "Content-Type: application/json" \
      #       --data "{\"name\": \"${{ github.event.inputs.channel_name }}\",\"is_private\": ${{ github.event.inputs.is_private }} }")
          
      #     echo "API Response: $response"
      #     status=$(echo $response | jq -r '.ok')
          
      #     if [$status=true]; then
      #       channel_id=$(echo $response | jq -r '.channel.id')
      #       echo "Channel ID: $channel_id"
      #       echo "CHANNEL_ID=$channel_id" >> $GITHUB_ENV
      
      #     else
      #       echo "Failed to create Slack channel. Channel ID is null."
      #       error=$(echo $response | jq -r '.error')
      #       error_message="${error//_/ }
      #       echo "Error: $error_message"
      #       echo "CREATE_CHANNEL_ERROR=$error_message" >> $GITHUB_ENV
      #       exit 1
      #     fi

      - name: Log If Create Channel Request Fails
        if: failure()
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(github.event.inputs.port_payload).context.runId }}
          logMessage: "Failed to create slack channel >>> ${{env.CREATE_CHANNEL_ERROR}}"

      - name: Log If Create Channel Request is Successful
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(github.event.inputs.port_payload).context.runId }}
          logMessage: "Channel created successfully, channel Id: ${{env.CHANNEL_ID}}"
          
      - name: Add Members to Slack Channel
        id: add_members
        if: success()
        env:
          SLACK_TOKEN: ${{ secrets.BOT_USER_OAUTH_TOKEN }}
          CHANNEL_ID: C06QYNQQZU3
        run: |
          MEMBER_EMAILS=${{ toJSON(github.event.inputs.members) }}
          for email in $(echo $MEMBER_EMAILS | jq -r '.[]'); do
            user_response=$(curl -s -X GET "https://slack.com/api/users.lookupByEmail?email=$email" \
              -H "Authorization: Bearer $SLACK_TOKEN")
      
            get_user_response=$(echo $user_response | jq -r '.ok')
      
            if [[ "$get_user_response" == "true" ]]; then
              user_id=$(echo $user_response | jq -r '.user.id')
              invite_response=$(curl -s -X POST "https://slack.com/api/conversations.invite" \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer $SLACK_TOKEN" \
                --data "{\"channel\":\"$CHANNEL_ID\",\"users\":\"$user_id\"}")
      
              status=$(echo $invite_response | jq -r '.ok')
              if [[ "$status" == "false" ]]; then
                error=$(echo $invite_response | jq -r '.error')
                error="${error//_/ }"
                error_message="Failed to invite $email to channel: $error"
                echo $error_message
                echo "ADD_MEMBER_TO_CHANNEL_ERROR=$error_message" >> $GITHUB_ENV
                exit 1
              fi
            else
              error=$(echo $user_response | jq -r '.error')
              error="${error//_/ }"
              error_message="Could not get user details for $email: $error"
              echo $error_message
              echo "ADD_MEMBER_TO_CHANNEL_ERROR=$error_message" >> $GITHUB_ENV
              exit 1 
            fi
          done

      - name: Log If Request to Add Members Fails
        if: failure()
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(github.event.inputs.port_payload).context.runId }}
          logMessage: "${{env.ADD_MEMBER_TO_CHANNEL_ERROR}}"

      - name: Log If Request to Add Members is Successful
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(github.event.inputs.port_payload).context.runId }}
          logMessage: "Successfully added members to channel"
